// Package qmclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package qmclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
	MutualTLSScopes  mutualTLSContextKey  = "MutualTLS.Scopes"
)

// AdminBilletMetadataResponse Response body for a billet metadata record.
type AdminBilletMetadataResponse struct {
	AssociatedAwsRoles []string `json:"associated_aws_roles"`
	AssociatedGcpSas   []string `json:"associated_gcp_sas"`
	Description        string   `json:"description"`
	Name               string   `json:"name"`
	Tags               []string `json:"tags"`
	UpdatedAt          string   `json:"updated_at"`
}

// BilletDiscoveryForm Form body for the billet discovery request.
type BilletDiscoveryForm struct {
	SubjectToken     *string `json:"subject_token,omitempty"`
	SubjectTokenType *string `json:"subject_token_type,omitempty"`
}

// BilletDiscoveryResponse JSON response for billet discovery.
type BilletDiscoveryResponse struct {
	Billets         []string `json:"billets"`
	CedarBillets    []string `json:"cedar_billets"`
	ImplicitBillets []string `json:"implicit_billets"`
}

// BilletListItem Represents a billet in the list response.
type BilletListItem struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// BilletMetadataResponse Response body for billet metadata.
type BilletMetadataResponse struct {
	AssociatedAwsRoles []string `json:"associated_aws_roles"`
	AssociatedGcpSas   []string `json:"associated_gcp_sas"`
	Description        string   `json:"description"`
	Name               string   `json:"name"`
}

// BilletWithPolicies Response for GET /admin/billets/{name} — includes policies.
type BilletWithPolicies struct {
	AssociatedAwsRoles []string        `json:"associated_aws_roles"`
	AssociatedGcpSas   []string        `json:"associated_gcp_sas"`
	Description        string          `json:"description"`
	Name               string          `json:"name"`
	Policies           []PolicySummary `json:"policies"`
	Tags               []string        `json:"tags"`
	UpdatedAt          string          `json:"updated_at"`
}

// CreateBilletRequest Request body for creating a billet.
type CreateBilletRequest struct {
	AssociatedAwsRoles *[]string `json:"associated_aws_roles,omitempty"`
	AssociatedGcpSas   *[]string `json:"associated_gcp_sas,omitempty"`
	Description        *string   `json:"description,omitempty"`
	Name               string    `json:"name"`
	Tags               *[]string `json:"tags,omitempty"`
}

// CreatePolicyRequest Request body for creating a policy under a billet.
type CreatePolicyRequest struct {
	Description *string `json:"description,omitempty"`
	Statement   string  `json:"statement"`
}

// DiscoveryDocument OpenID Connect discovery document for Quartermaster.
//
// Serves at `GET /.well-known/openid-configuration` and provides
// cloud provider IAM systems with the information needed to verify
// Quartermaster-issued JWTs.
type DiscoveryDocument struct {
	// ClaimsSupported Supported claims in issued tokens.
	ClaimsSupported []string `json:"claims_supported"`

	// IdTokenSigningAlgValuesSupported Supported signing algorithms for ID tokens.
	IdTokenSigningAlgValuesSupported []string `json:"id_token_signing_alg_values_supported"`

	// Issuer The issuer URL matching Quartermaster's configured issuer.
	Issuer string `json:"issuer"`

	// JwksUri The URL of the JWKS endpoint (issuer + "/jwks.json").
	JwksUri string `json:"jwks_uri"`

	// ResponseTypesSupported Supported response types.
	ResponseTypesSupported []string `json:"response_types_supported"`

	// SubjectTypesSupported Supported subject types.
	SubjectTypesSupported []string `json:"subject_types_supported"`
}

// ErrorBody The JSON body structure for error responses, following OAuth 2.0 conventions.
type ErrorBody struct {
	Error            string `json:"error"`
	ErrorDescription string `json:"error_description"`
}

// HealthChecks defines model for HealthChecks.
type HealthChecks struct {
	Datastore  string `json:"datastore"`
	PolicySync string `json:"policy_sync"`
	SigningKey string `json:"signing_key"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks HealthChecks `json:"checks"`
	Status string       `json:"status"`
}

// PolicyResponse Response body for a policy record.
type PolicyResponse struct {
	Description string `json:"description"`
	Id          string `json:"id"`
	Statement   string `json:"statement"`
}

// PolicySummary Summary of a policy attached to a billet.
type PolicySummary struct {
	Description string `json:"description"`
	Id          string `json:"id"`
	Statement   string `json:"statement"`
}

// TokenExchangeForm Form body for the token exchange request (application/x-www-form-urlencoded).
type TokenExchangeForm struct {
	Audience         *string `json:"audience,omitempty"`
	Billets          *string `json:"billets,omitempty"`
	Csr              *string `json:"csr,omitempty"`
	GrantType        *string `json:"grant_type,omitempty"`
	SubjectToken     *string `json:"subject_token,omitempty"`
	SubjectTokenType *string `json:"subject_token_type,omitempty"`
}

// TokenExchangeResponse JSON response for a successful token exchange.
type TokenExchangeResponse struct {
	AccessToken      string  `json:"access_token"`
	CertificateChain *string `json:"certificate_chain,omitempty"`
	ExpiresIn        int64   `json:"expires_in"`
	IssuedTokenType  string  `json:"issued_token_type"`
	TokenType        string  `json:"token_type"`
}

// UpdateBilletRequest Request body for updating a billet.
type UpdateBilletRequest struct {
	AssociatedAwsRoles *[]string `json:"associated_aws_roles,omitempty"`
	AssociatedGcpSas   *[]string `json:"associated_gcp_sas,omitempty"`
	Description        *string   `json:"description,omitempty"`
	Tags               *[]string `json:"tags,omitempty"`
}

// UpdatePolicyRequest Request body for updating a policy under a billet.
type UpdatePolicyRequest struct {
	Description *string `json:"description,omitempty"`
	Statement   string  `json:"statement"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// mutualTLSContextKey is the context key for MutualTLS security scheme
type mutualTLSContextKey string

// CreateBilletJSONRequestBody defines body for CreateBillet for application/json ContentType.
type CreateBilletJSONRequestBody = CreateBilletRequest

// UpdateBilletJSONRequestBody defines body for UpdateBillet for application/json ContentType.
type UpdateBilletJSONRequestBody = UpdateBilletRequest

// CreatePolicyJSONRequestBody defines body for CreatePolicy for application/json ContentType.
type CreatePolicyJSONRequestBody = CreatePolicyRequest

// UpdatePolicyJSONRequestBody defines body for UpdatePolicy for application/json ContentType.
type UpdatePolicyJSONRequestBody = UpdatePolicyRequest

// BilletDiscoveryFormdataRequestBody defines body for BilletDiscovery for application/x-www-form-urlencoded ContentType.
type BilletDiscoveryFormdataRequestBody = BilletDiscoveryForm

// TokenExchangeFormdataRequestBody defines body for TokenExchange for application/x-www-form-urlencoded ContentType.
type TokenExchangeFormdataRequestBody = TokenExchangeForm

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// OpenidConfiguration request
	OpenidConfiguration(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListBillets request
	ListBillets(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBilletWithBody request with any body
	CreateBilletWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateBillet(ctx context.Context, body CreateBilletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBillet request
	DeleteBillet(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminBillet request
	GetAdminBillet(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateBilletWithBody request with any body
	UpdateBilletWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateBillet(ctx context.Context, name string, body UpdateBilletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPolicies request
	ListPolicies(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePolicyWithBody request with any body
	CreatePolicyWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePolicy(ctx context.Context, name string, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeletePolicy request
	DeletePolicy(ctx context.Context, name string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPolicy request
	GetPolicy(ctx context.Context, name string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdatePolicyWithBody request with any body
	UpdatePolicyWithBody(ctx context.Context, name string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdatePolicy(ctx context.Context, name string, id string, body UpdatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BilletDiscoveryWithBody request with any body
	BilletDiscoveryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BilletDiscoveryWithFormdataBody(ctx context.Context, body BilletDiscoveryFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBilletMetadata request
	GetBilletMetadata(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CaChain request
	CaChain(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Healthz request
	Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Jwks request
	Jwks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TokenExchangeWithBody request with any body
	TokenExchangeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TokenExchangeWithFormdataBody(ctx context.Context, body TokenExchangeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) OpenidConfiguration(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOpenidConfigurationRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListBillets(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBilletsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBilletWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBilletRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBillet(ctx context.Context, body CreateBilletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBilletRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBillet(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBilletRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminBillet(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminBilletRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateBilletWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateBilletRequestWithBody(c.Server, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateBillet(ctx context.Context, name string, body UpdateBilletJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateBilletRequest(c.Server, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPolicies(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPoliciesRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePolicyWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePolicyRequestWithBody(c.Server, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePolicy(ctx context.Context, name string, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePolicyRequest(c.Server, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeletePolicy(ctx context.Context, name string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePolicyRequest(c.Server, name, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPolicy(ctx context.Context, name string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPolicyRequest(c.Server, name, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdatePolicyWithBody(ctx context.Context, name string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePolicyRequestWithBody(c.Server, name, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdatePolicy(ctx context.Context, name string, id string, body UpdatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePolicyRequest(c.Server, name, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BilletDiscoveryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBilletDiscoveryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BilletDiscoveryWithFormdataBody(ctx context.Context, body BilletDiscoveryFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBilletDiscoveryRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBilletMetadata(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBilletMetadataRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CaChain(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCaChainRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Jwks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewJwksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TokenExchangeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTokenExchangeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TokenExchangeWithFormdataBody(ctx context.Context, body TokenExchangeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTokenExchangeRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewOpenidConfigurationRequest generates requests for OpenidConfiguration
func NewOpenidConfigurationRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/.well-known/openid-configuration")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListBilletsRequest generates requests for ListBillets
func NewListBilletsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateBilletRequest calls the generic CreateBillet builder with application/json body
func NewCreateBilletRequest(server string, body CreateBilletJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateBilletRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateBilletRequestWithBody generates requests for CreateBillet with any type of body
func NewCreateBilletRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteBilletRequest generates requests for DeleteBillet
func NewDeleteBilletRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminBilletRequest generates requests for GetAdminBillet
func NewGetAdminBilletRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateBilletRequest calls the generic UpdateBillet builder with application/json body
func NewUpdateBilletRequest(server string, name string, body UpdateBilletJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateBilletRequestWithBody(server, name, "application/json", bodyReader)
}

// NewUpdateBilletRequestWithBody generates requests for UpdateBillet with any type of body
func NewUpdateBilletRequestWithBody(server string, name string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListPoliciesRequest generates requests for ListPolicies
func NewListPoliciesRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets/%s/policies", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePolicyRequest calls the generic CreatePolicy builder with application/json body
func NewCreatePolicyRequest(server string, name string, body CreatePolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePolicyRequestWithBody(server, name, "application/json", bodyReader)
}

// NewCreatePolicyRequestWithBody generates requests for CreatePolicy with any type of body
func NewCreatePolicyRequestWithBody(server string, name string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets/%s/policies", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeletePolicyRequest generates requests for DeletePolicy
func NewDeletePolicyRequest(server string, name string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets/%s/policies/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPolicyRequest generates requests for GetPolicy
func NewGetPolicyRequest(server string, name string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets/%s/policies/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdatePolicyRequest calls the generic UpdatePolicy builder with application/json body
func NewUpdatePolicyRequest(server string, name string, id string, body UpdatePolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdatePolicyRequestWithBody(server, name, id, "application/json", bodyReader)
}

// NewUpdatePolicyRequestWithBody generates requests for UpdatePolicy with any type of body
func NewUpdatePolicyRequestWithBody(server string, name string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/billets/%s/policies/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBilletDiscoveryRequestWithFormdataBody calls the generic BilletDiscovery builder with application/x-www-form-urlencoded body
func NewBilletDiscoveryRequestWithFormdataBody(server string, body BilletDiscoveryFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewBilletDiscoveryRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewBilletDiscoveryRequestWithBody generates requests for BilletDiscovery with any type of body
func NewBilletDiscoveryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billets/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetBilletMetadataRequest generates requests for GetBilletMetadata
func NewGetBilletMetadataRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/billets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCaChainRequest generates requests for CaChain
func NewCaChainRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ca/chain.pem")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthzRequest generates requests for Healthz
func NewHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewJwksRequest generates requests for Jwks
func NewJwksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/jwks.json")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTokenExchangeRequestWithFormdataBody calls the generic TokenExchange builder with application/x-www-form-urlencoded body
func NewTokenExchangeRequestWithFormdataBody(server string, body TokenExchangeFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewTokenExchangeRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewTokenExchangeRequestWithBody generates requests for TokenExchange with any type of body
func NewTokenExchangeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// OpenidConfigurationWithResponse request
	OpenidConfigurationWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OpenidConfigurationHTTP, error)

	// ListBilletsWithResponse request
	ListBilletsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBilletsHTTP, error)

	// CreateBilletWithBodyWithResponse request with any body
	CreateBilletWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBilletHTTP, error)

	CreateBilletWithResponse(ctx context.Context, body CreateBilletJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBilletHTTP, error)

	// DeleteBilletWithResponse request
	DeleteBilletWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*DeleteBilletHTTP, error)

	// GetAdminBilletWithResponse request
	GetAdminBilletWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetAdminBilletHTTP, error)

	// UpdateBilletWithBodyWithResponse request with any body
	UpdateBilletWithBodyWithResponse(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateBilletHTTP, error)

	UpdateBilletWithResponse(ctx context.Context, name string, body UpdateBilletJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateBilletHTTP, error)

	// ListPoliciesWithResponse request
	ListPoliciesWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*ListPoliciesHTTP, error)

	// CreatePolicyWithBodyWithResponse request with any body
	CreatePolicyWithBodyWithResponse(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePolicyHTTP, error)

	CreatePolicyWithResponse(ctx context.Context, name string, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePolicyHTTP, error)

	// DeletePolicyWithResponse request
	DeletePolicyWithResponse(ctx context.Context, name string, id string, reqEditors ...RequestEditorFn) (*DeletePolicyHTTP, error)

	// GetPolicyWithResponse request
	GetPolicyWithResponse(ctx context.Context, name string, id string, reqEditors ...RequestEditorFn) (*GetPolicyHTTP, error)

	// UpdatePolicyWithBodyWithResponse request with any body
	UpdatePolicyWithBodyWithResponse(ctx context.Context, name string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdatePolicyHTTP, error)

	UpdatePolicyWithResponse(ctx context.Context, name string, id string, body UpdatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdatePolicyHTTP, error)

	// BilletDiscoveryWithBodyWithResponse request with any body
	BilletDiscoveryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BilletDiscoveryHTTP, error)

	BilletDiscoveryWithFormdataBodyWithResponse(ctx context.Context, body BilletDiscoveryFormdataRequestBody, reqEditors ...RequestEditorFn) (*BilletDiscoveryHTTP, error)

	// GetBilletMetadataWithResponse request
	GetBilletMetadataWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetBilletMetadataHTTP, error)

	// CaChainWithResponse request
	CaChainWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CaChainHTTP, error)

	// HealthzWithResponse request
	HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHTTP, error)

	// JwksWithResponse request
	JwksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*JwksHTTP, error)

	// TokenExchangeWithBodyWithResponse request with any body
	TokenExchangeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TokenExchangeHTTP, error)

	TokenExchangeWithFormdataBodyWithResponse(ctx context.Context, body TokenExchangeFormdataRequestBody, reqEditors ...RequestEditorFn) (*TokenExchangeHTTP, error)
}

type OpenidConfigurationHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DiscoveryDocument
}

// Status returns HTTPResponse.Status
func (r OpenidConfigurationHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OpenidConfigurationHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OpenidConfigurationHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListBilletsHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]BilletListItem
	JSON401      *ErrorBody
	JSON403      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r ListBilletsHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBilletsHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListBilletsHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateBilletHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *AdminBilletMetadataResponse
	JSON401      *ErrorBody
	JSON403      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r CreateBilletHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBilletHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateBilletHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteBilletHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *ErrorBody
	JSON403      *ErrorBody
	JSON404      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r DeleteBilletHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBilletHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteBilletHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAdminBilletHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BilletWithPolicies
	JSON401      *ErrorBody
	JSON403      *ErrorBody
	JSON404      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r GetAdminBilletHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminBilletHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAdminBilletHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateBilletHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AdminBilletMetadataResponse
	JSON401      *ErrorBody
	JSON403      *ErrorBody
	JSON404      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r UpdateBilletHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateBilletHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateBilletHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListPoliciesHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]PolicyResponse
	JSON401      *ErrorBody
	JSON403      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r ListPoliciesHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPoliciesHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPoliciesHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreatePolicyHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *PolicyResponse
	JSON401      *ErrorBody
	JSON403      *ErrorBody
	JSON404      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r CreatePolicyHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePolicyHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePolicyHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeletePolicyHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *ErrorBody
	JSON403      *ErrorBody
	JSON404      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r DeletePolicyHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeletePolicyHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeletePolicyHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPolicyHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PolicyResponse
	JSON401      *ErrorBody
	JSON403      *ErrorBody
	JSON404      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r GetPolicyHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPolicyHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPolicyHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdatePolicyHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PolicyResponse
	JSON401      *ErrorBody
	JSON403      *ErrorBody
	JSON404      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r UpdatePolicyHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdatePolicyHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdatePolicyHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type BilletDiscoveryHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BilletDiscoveryResponse
	JSON400      *ErrorBody
	JSON401      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r BilletDiscoveryHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BilletDiscoveryHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BilletDiscoveryHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetBilletMetadataHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BilletMetadataResponse
	JSON401      *ErrorBody
	JSON403      *ErrorBody
	JSON404      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r GetBilletMetadataHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBilletMetadataHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBilletMetadataHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CaChainHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r CaChainHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CaChainHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CaChainHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthzHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthzHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type JwksHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r JwksHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r JwksHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r JwksHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TokenExchangeHTTP struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenExchangeResponse
	JSON400      *ErrorBody
	JSON401      *ErrorBody
}

// Status returns HTTPResponse.Status
func (r TokenExchangeHTTP) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TokenExchangeHTTP) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TokenExchangeHTTP) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// OpenidConfigurationWithResponse request returning *OpenidConfigurationHTTP
func (c *ClientWithResponses) OpenidConfigurationWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OpenidConfigurationHTTP, error) {
	rsp, err := c.OpenidConfiguration(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOpenidConfigurationHTTP(rsp)
}

// ListBilletsWithResponse request returning *ListBilletsHTTP
func (c *ClientWithResponses) ListBilletsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBilletsHTTP, error) {
	rsp, err := c.ListBillets(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBilletsHTTP(rsp)
}

// CreateBilletWithBodyWithResponse request with arbitrary body returning *CreateBilletHTTP
func (c *ClientWithResponses) CreateBilletWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBilletHTTP, error) {
	rsp, err := c.CreateBilletWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBilletHTTP(rsp)
}

func (c *ClientWithResponses) CreateBilletWithResponse(ctx context.Context, body CreateBilletJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBilletHTTP, error) {
	rsp, err := c.CreateBillet(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBilletHTTP(rsp)
}

// DeleteBilletWithResponse request returning *DeleteBilletHTTP
func (c *ClientWithResponses) DeleteBilletWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*DeleteBilletHTTP, error) {
	rsp, err := c.DeleteBillet(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBilletHTTP(rsp)
}

// GetAdminBilletWithResponse request returning *GetAdminBilletHTTP
func (c *ClientWithResponses) GetAdminBilletWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetAdminBilletHTTP, error) {
	rsp, err := c.GetAdminBillet(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminBilletHTTP(rsp)
}

// UpdateBilletWithBodyWithResponse request with arbitrary body returning *UpdateBilletHTTP
func (c *ClientWithResponses) UpdateBilletWithBodyWithResponse(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateBilletHTTP, error) {
	rsp, err := c.UpdateBilletWithBody(ctx, name, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateBilletHTTP(rsp)
}

func (c *ClientWithResponses) UpdateBilletWithResponse(ctx context.Context, name string, body UpdateBilletJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateBilletHTTP, error) {
	rsp, err := c.UpdateBillet(ctx, name, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateBilletHTTP(rsp)
}

// ListPoliciesWithResponse request returning *ListPoliciesHTTP
func (c *ClientWithResponses) ListPoliciesWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*ListPoliciesHTTP, error) {
	rsp, err := c.ListPolicies(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPoliciesHTTP(rsp)
}

// CreatePolicyWithBodyWithResponse request with arbitrary body returning *CreatePolicyHTTP
func (c *ClientWithResponses) CreatePolicyWithBodyWithResponse(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePolicyHTTP, error) {
	rsp, err := c.CreatePolicyWithBody(ctx, name, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePolicyHTTP(rsp)
}

func (c *ClientWithResponses) CreatePolicyWithResponse(ctx context.Context, name string, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePolicyHTTP, error) {
	rsp, err := c.CreatePolicy(ctx, name, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePolicyHTTP(rsp)
}

// DeletePolicyWithResponse request returning *DeletePolicyHTTP
func (c *ClientWithResponses) DeletePolicyWithResponse(ctx context.Context, name string, id string, reqEditors ...RequestEditorFn) (*DeletePolicyHTTP, error) {
	rsp, err := c.DeletePolicy(ctx, name, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePolicyHTTP(rsp)
}

// GetPolicyWithResponse request returning *GetPolicyHTTP
func (c *ClientWithResponses) GetPolicyWithResponse(ctx context.Context, name string, id string, reqEditors ...RequestEditorFn) (*GetPolicyHTTP, error) {
	rsp, err := c.GetPolicy(ctx, name, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPolicyHTTP(rsp)
}

// UpdatePolicyWithBodyWithResponse request with arbitrary body returning *UpdatePolicyHTTP
func (c *ClientWithResponses) UpdatePolicyWithBodyWithResponse(ctx context.Context, name string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdatePolicyHTTP, error) {
	rsp, err := c.UpdatePolicyWithBody(ctx, name, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdatePolicyHTTP(rsp)
}

func (c *ClientWithResponses) UpdatePolicyWithResponse(ctx context.Context, name string, id string, body UpdatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdatePolicyHTTP, error) {
	rsp, err := c.UpdatePolicy(ctx, name, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdatePolicyHTTP(rsp)
}

// BilletDiscoveryWithBodyWithResponse request with arbitrary body returning *BilletDiscoveryHTTP
func (c *ClientWithResponses) BilletDiscoveryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BilletDiscoveryHTTP, error) {
	rsp, err := c.BilletDiscoveryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBilletDiscoveryHTTP(rsp)
}

func (c *ClientWithResponses) BilletDiscoveryWithFormdataBodyWithResponse(ctx context.Context, body BilletDiscoveryFormdataRequestBody, reqEditors ...RequestEditorFn) (*BilletDiscoveryHTTP, error) {
	rsp, err := c.BilletDiscoveryWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBilletDiscoveryHTTP(rsp)
}

// GetBilletMetadataWithResponse request returning *GetBilletMetadataHTTP
func (c *ClientWithResponses) GetBilletMetadataWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetBilletMetadataHTTP, error) {
	rsp, err := c.GetBilletMetadata(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBilletMetadataHTTP(rsp)
}

// CaChainWithResponse request returning *CaChainHTTP
func (c *ClientWithResponses) CaChainWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CaChainHTTP, error) {
	rsp, err := c.CaChain(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCaChainHTTP(rsp)
}

// HealthzWithResponse request returning *HealthzHTTP
func (c *ClientWithResponses) HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHTTP, error) {
	rsp, err := c.Healthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzHTTP(rsp)
}

// JwksWithResponse request returning *JwksHTTP
func (c *ClientWithResponses) JwksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*JwksHTTP, error) {
	rsp, err := c.Jwks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseJwksHTTP(rsp)
}

// TokenExchangeWithBodyWithResponse request with arbitrary body returning *TokenExchangeHTTP
func (c *ClientWithResponses) TokenExchangeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TokenExchangeHTTP, error) {
	rsp, err := c.TokenExchangeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTokenExchangeHTTP(rsp)
}

func (c *ClientWithResponses) TokenExchangeWithFormdataBodyWithResponse(ctx context.Context, body TokenExchangeFormdataRequestBody, reqEditors ...RequestEditorFn) (*TokenExchangeHTTP, error) {
	rsp, err := c.TokenExchangeWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTokenExchangeHTTP(rsp)
}

// ParseOpenidConfigurationHTTP parses an HTTP response from a OpenidConfigurationWithResponse call
func ParseOpenidConfigurationHTTP(rsp *http.Response) (*OpenidConfigurationHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OpenidConfigurationHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DiscoveryDocument
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListBilletsHTTP parses an HTTP response from a ListBilletsWithResponse call
func ParseListBilletsHTTP(rsp *http.Response) (*ListBilletsHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBilletsHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []BilletListItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseCreateBilletHTTP parses an HTTP response from a CreateBilletWithResponse call
func ParseCreateBilletHTTP(rsp *http.Response) (*CreateBilletHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBilletHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AdminBilletMetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteBilletHTTP parses an HTTP response from a DeleteBilletWithResponse call
func ParseDeleteBilletHTTP(rsp *http.Response) (*DeleteBilletHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBilletHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetAdminBilletHTTP parses an HTTP response from a GetAdminBilletWithResponse call
func ParseGetAdminBilletHTTP(rsp *http.Response) (*GetAdminBilletHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminBilletHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BilletWithPolicies
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateBilletHTTP parses an HTTP response from a UpdateBilletWithResponse call
func ParseUpdateBilletHTTP(rsp *http.Response) (*UpdateBilletHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateBilletHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AdminBilletMetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListPoliciesHTTP parses an HTTP response from a ListPoliciesWithResponse call
func ParseListPoliciesHTTP(rsp *http.Response) (*ListPoliciesHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPoliciesHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []PolicyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseCreatePolicyHTTP parses an HTTP response from a CreatePolicyWithResponse call
func ParseCreatePolicyHTTP(rsp *http.Response) (*CreatePolicyHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePolicyHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PolicyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDeletePolicyHTTP parses an HTTP response from a DeletePolicyWithResponse call
func ParseDeletePolicyHTTP(rsp *http.Response) (*DeletePolicyHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeletePolicyHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetPolicyHTTP parses an HTTP response from a GetPolicyWithResponse call
func ParseGetPolicyHTTP(rsp *http.Response) (*GetPolicyHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPolicyHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdatePolicyHTTP parses an HTTP response from a UpdatePolicyWithResponse call
func ParseUpdatePolicyHTTP(rsp *http.Response) (*UpdatePolicyHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdatePolicyHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseBilletDiscoveryHTTP parses an HTTP response from a BilletDiscoveryWithResponse call
func ParseBilletDiscoveryHTTP(rsp *http.Response) (*BilletDiscoveryHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BilletDiscoveryHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BilletDiscoveryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetBilletMetadataHTTP parses an HTTP response from a GetBilletMetadataWithResponse call
func ParseGetBilletMetadataHTTP(rsp *http.Response) (*GetBilletMetadataHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBilletMetadataHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BilletMetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCaChainHTTP parses an HTTP response from a CaChainWithResponse call
func ParseCaChainHTTP(rsp *http.Response) (*CaChainHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CaChainHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHealthzHTTP parses an HTTP response from a HealthzWithResponse call
func ParseHealthzHTTP(rsp *http.Response) (*HealthzHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseJwksHTTP parses an HTTP response from a JwksWithResponse call
func ParseJwksHTTP(rsp *http.Response) (*JwksHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &JwksHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTokenExchangeHTTP parses an HTTP response from a TokenExchangeWithResponse call
func ParseTokenExchangeHTTP(rsp *http.Response) (*TokenExchangeHTTP, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TokenExchangeHTTP{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenExchangeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}
